version: '3'

services:
  # Laravelを動かすコンテナ
  app:
    container_name: vue_online_store_app
    build: ./docker/app
    ports:
      - "8000:80" # ホストの8000ポートをコンテナの80ポートにマッピング
    volumes:
      - .:/var/www/html # プロジェクト全体を同期
    depends_on:
      - db # MySQLコンテナが起動してからアプリケーションを起動

  # MySQLを動かすコンテナ
  db:
    image: mysql:8.0
    container_name: vue_online_store_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vue_online_store
      # MYSQL_USER: root
      # MYSQL_PASSWORD: root
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/db/volume:/var/lib/mysql # データ永続化
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf # 設定ファイル
    ports:
      - "3306:3306" # ホストとコンテナのMySQLポートをマッピング

  # phpMyAdminを動かすコンテナ
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: vue_online_store_phpmyadmin
    environment:
      PMA_HOST: db # MySQLコンテナ名を指定
      PMA_PORT: 3306
    ports:
      - "8080:80" # phpMyAdminにアクセスするためのポート
    depends_on:
      - db # MySQLコンテナが先に起動

  # Mailpitを動かすコンテナ（ローカルメールサーバ）
  mailpit:
    image: axllent/mailpit
    container_name: vue_online_store_mailpit
    ports:
      - "1025:1025" # SMTP用ポート
      - "8025:8025" # Mailpit UI用ポート
