version: '3'

services:
  app:
    container_name: vue_online_store_app
    build: ./docker/app
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: vue_online_store_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vue_online_store
      # MYSQL_USER: root
      # MYSQL_PASSWORD: root
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/db/volume:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: vue_online_store_phpmyadmin
    environment:
      PMA_HOST: vue_online_store_db
      PMA_PORT: 3306
    ports:
      - "8080:80"
    depends_on:
      - db

  mailpit:
    image: axllent/mailpit
    container_name: vue_online_store_mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
